// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceMetadata } from "./ChoiceMetadata";

export interface Choice { id: string, description: string, target_node_id: string | null, weight: number, feasibility_score: number | null, consequences: Array<string>, metadata: ChoiceMetadata, }