// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskLevel } from "./RiskLevel";

export interface ChoiceMetadata { confidence_score: number | null, risk_level: RiskLevel, time_estimate: string | null, dependencies: Array<string>, }