// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoherenceIssueType } from "./CoherenceIssueType";
import type { IssueSeverity } from "./IssueSeverity";

export interface CoherenceIssue { issue_type: CoherenceIssueType, description: string, severity: IssueSeverity, affected_nodes: Array<string>, }