// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoherenceIssue } from "./CoherenceIssue";

export interface CoherenceReport { is_coherent: boolean, confidence_score: number, issues: Array<CoherenceIssue>, suggestions: Array<string>, }