// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EdgeMetadata { decision_timestamp: string | null, user_feedback: string | null, success_probability: number | null, }