// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TechnicalDetail } from "./TechnicalDetail";
import type { ValidationStatus } from "./ValidationStatus";

export interface NodeMetadata { generated_by_ai: boolean, validation_status: ValidationStatus, user_annotations: Array<string>, technical_details: Array<TechnicalDetail>, }