// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExperienceLevel } from "./ExperienceLevel";

export interface ProjectConstraints { timeline: string | null, team_size: number | null, experience_level: ExperienceLevel, budget: string | null, technical_constraints: Array<string>, business_constraints: Array<string>, }