// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionContext } from "./QuestionContext";
import type { QuestionOption } from "./QuestionOption";
import type { QuestionType } from "./QuestionType";
import type { ValidationRules } from "./ValidationRules";

export interface Question { id: string, question_type: QuestionType, prompt: string, options: Array<QuestionOption> | null, validation_rules: ValidationRules, context: QuestionContext, created_at: string, }