// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QuestionOption { id: string, label: string, value: any, description: string | null, }