// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SessionMetadata { session_id: string, user_id: string | null, started_at: string, last_activity: string, }