// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";
import type { NodeMetadata } from "./NodeMetadata";
import type { NodeState } from "./NodeState";
import type { NodeType } from "./NodeType";
import type { Position } from "./Position";

export interface StoryNode { id: string, node_type: NodeType, situation: string, choices: Array<Choice>, position: Position, state: NodeState, complexity_score: number | null, metadata: NodeMetadata, created_at: string, }