// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeMetadata } from "./EdgeMetadata";

export interface StoryEdge { id: string, from_node_id: string, to_node_id: string, choice_id: string, traversal_count: number, metadata: EdgeMetadata, }