// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StoryAnalytics { total_nodes: number, completion_percentage: number, average_complexity: number, decision_points: number, estimated_timeline: string | null, }