// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoryEdge } from "./StoryEdge";
import type { StoryMetadata } from "./StoryMetadata";
import type { StoryNode } from "./StoryNode";

export interface StoryGraph { id: string, title: string, description: string | null, nodes: Record<string, StoryNode>, edges: Array<StoryEdge>, root_node_id: string | null, current_node_id: string | null, metadata: StoryMetadata, created_at: string, updated_at: string, }