// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectConstraints } from "./ProjectConstraints";
import type { SessionMetadata } from "./SessionMetadata";
import type { UserResponse } from "./UserResponse";

export interface StoryContext { previous_choices: Array<string>, user_responses: Array<UserResponse>, current_constraints: ProjectConstraints, session_metadata: SessionMetadata, }