// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectConstraints } from "./ProjectConstraints";
import type { StoryAnalytics } from "./StoryAnalytics";

export interface StoryMetadata { owner_id: string | null, is_public: boolean, tags: Array<string>, project_constraints: ProjectConstraints, analytics: StoryAnalytics, }