// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportanceLevel } from "./ImportanceLevel";

export interface TechnicalDetail { category: string, description: string, importance: ImportanceLevel, }