// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";

export interface UncertaintyContext { uncertainty_level: number, missing_context: Array<string>, conflicting_choices: Array<Choice>, ambiguous_requirements: Array<string>, }