// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValidationRules { required: boolean, min_length: number | null, max_length: number | null, pattern: string | null, custom_validator: string | null, }